ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.yoke.gainful.server.ApplicationKt.module ]
    }
}

database {
    driver = "org.postgresql.Driver"
    driver = ${?DB_DRIVER}
    url = "jdbc:postgresql://localhost:5432/gainful"
    url = ${?DB_URL}
    user = ""
    user = ${?DB_USER}
    password = ""
    password = ${?DB_PASSWORD}
}

jwt {
    secret = "gainful-dev-secret-key-change-in-production"
    secret = ${?JWT_SECRET}
    issuer = "gainful"
    audience = "gainful-users"
    realm = "gainful-server"
    expiresIn = 900000
    refreshExpiresIn = 2592000000
}

upload {
    dir = "data/uploads/avatars"
    dir = ${?UPLOAD_DIR}
    maxFileSizeBytes = 2097152
}
